# Generated by Django 2.0.2 on 2018-03-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='india',
            name='Type',
            field=models.CharField(default='Teacher', max_length=20),
        ),
    ]
