# Generated by Django 2.0.2 on 2018-03-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_india_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='india',
            name='Type',
            field=models.CharField(choices=[('T', 'Teacher'), ('S', 'Student')], max_length=1),
        ),
    ]
