# Generated by Django 2.0.2 on 2018-03-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180329_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='india',
            name='Type',
            field=models.CharField(choices=[('T', 'Teacher'), ('S', 'Student')], max_length=10),
        ),
    ]
