# Generated by Django 2.0.2 on 2018-03-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180329_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='india',
            name='Type',
        ),
        migrations.AddField(
            model_name='india',
            name='haha',
            field=models.CharField(default='Teacher', max_length=20),
        ),
    ]
