# Generated by Django 2.0.2 on 2018-03-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20180329_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='india',
            name='haha',
            field=models.CharField(choices=[('1', 'Student'), ('2', 'Teacher')], default='Teacher', max_length=20),
        ),
    ]
