# Generated by Django 2.0.2 on 2018-03-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20180329_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='india',
            name='haha',
            field=models.IntegerField(default=0),
        ),
    ]
