# Generated by Django 2.0.2 on 2018-03-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20180329_0420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='india',
            old_name='haha',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='india',
            name='hahaha',
        ),
    ]
