# Generated by Django 2.0.2 on 2018-03-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20180329_1246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='India',
            new_name='Data',
        ),
    ]
