# Generated by Django 2.0.2 on 2018-03-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20180329_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='account',
        ),
        migrations.RemoveField(
            model_name='data',
            name='email',
        ),
        migrations.RemoveField(
            model_name='data',
            name='password',
        ),
        migrations.RemoveField(
            model_name='data',
            name='username',
        ),
    ]
