# Generated by Django 2.0.2 on 2018-03-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20180329_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='account',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='email',
            field=models.CharField(default='a@b.com', max_length=20),
        ),
        migrations.AddField(
            model_name='data',
            name='password',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='data',
            name='username',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
