# Generated by Django 2.0.2 on 2018-03-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20180329_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentreg',
            fields=[
                ('username', models.CharField(default='NULL', max_length=20)),
                ('email', models.CharField(default='a@b.com', max_length=20)),
                ('password', models.CharField(default='0', max_length=20)),
                ('roll', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('account', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Teacherreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='NULL', max_length=20)),
                ('email', models.CharField(default='a@b.com', max_length=20)),
                ('password', models.CharField(default='0', max_length=20)),
                ('subject', models.CharField(default='0', max_length=20)),
                ('account', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
