# Generated by Django 2.0.2 on 2018-03-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20180330_1433'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Time',
            new_name='Timer',
        ),
    ]
