# Generated by Django 2.0.2 on 2018-04-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20180330_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aoa',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('_1', models.CharField(default='Not', max_length=20)),
                ('_2', models.CharField(default='Not', max_length=20)),
                ('_3', models.CharField(default='Not', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Timer',
        ),
    ]
