# Generated by Django 2.0.2 on 2018-04-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20180402_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoa',
            name='_4',
            field=models.CharField(default='Not', max_length=10),
        ),
        migrations.AddField(
            model_name='aoa',
            name='_5',
            field=models.CharField(default='Not', max_length=10),
        ),
        migrations.AddField(
            model_name='aoa',
            name='_6',
            field=models.CharField(default='Not', max_length=10),
        ),
        migrations.AddField(
            model_name='aoa',
            name='_7',
            field=models.CharField(default='Not', max_length=10),
        ),
    ]
